{% set name = "IlmBase" %}
{% set version = "2.3.0" %}
{% set sha256 = "456978d1a978a5f823c7c675f3f36b0ae14dba36638aeaa3c4b0e784f12a3862" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://github.com/openexr/openexr/releases/download/v{{ version }}/{{ name|lower }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1000
  skip: true  # [win and vc<14]
  run_exports:
    # https\://abi-laboratory.pro/\?view\=timeline\&l\=ilmbase
    - {{ pin_subpackage(name|lower, max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake  # [win]

  host:
    - zlib

test:
  commands:
    - test -f ${PREFIX}/include/OpenEXR/half.h                            # [unix]
    - test -f ${PREFIX}/include/OpenEXR/IlmThread.h                       # [unix]
    - test -f ${PREFIX}/include/OpenEXR/ImathMath.h                       # [unix]
    - test -f ${PREFIX}/include/OpenEXR/Iex.h                             # [unix]
    - test -f ${PREFIX}/include/OpenEXR/IexMathExc.h                      # [unix]
    - test -f ${PREFIX}/lib/libHalf.a                                     # [unix]
    - test -f ${PREFIX}/lib/libHalf${SHLIB_EXT}                           # [unix]
    - test -f ${PREFIX}/lib/libIlmThread.a                                # [unix]
    - test -f ${PREFIX}/lib/libIlmThread${SHLIB_EXT}                      # [unix]
    - test -f ${PREFIX}/lib/libImath.a                                    # [unix]
    - test -f ${PREFIX}/lib/libImath${SHLIB_EXT}                          # [unix]
    - test -f ${PREFIX}/lib/libIex.a                                      # [unix]
    - test -f ${PREFIX}/lib/libIex${SHLIB_EXT}                            # [unix]
    - test -f ${PREFIX}/lib/libIexMath.a                                  # [unix]
    - test -f ${PREFIX}/lib/libIexMath${SHLIB_EXT}                        # [unix]
    - if not exist %LIBRARY_PREFIX%\include\OpenEXR\half.h  exit 1        # [win]
    - if not exist %LIBRARY_PREFIX%\include\OpenEXR\IlmThread.h  exit 1   # [win]
    - if not exist %LIBRARY_PREFIX%\include\OpenEXR\ImathMath.h  exit 1   # [win]
    - if not exist %LIBRARY_PREFIX%\include\OpenEXR\Iex.h  exit 1         # [win]
    - if not exist %LIBRARY_PREFIX%\include\OpenEXR\IexMathExc.h exit 1   # [win]
    - if not exist %LIBRARY_PREFIX%\lib\Half.lib  exit 1                  # [win]
    - if not exist %LIBRARY_PREFIX%\lib\Half_static.lib  exit 1           # [win]
    - if not exist %LIBRARY_PREFIX%\lib\IlmThread.lib  exit 1             # [win]
    - if not exist %LIBRARY_PREFIX%\lib\Imath.lib  exit 1                 # [win]
    - if not exist %LIBRARY_PREFIX%\lib\Iex.lib  exit 1                   # [win]
    - if not exist %LIBRARY_PREFIX%\lib\IexMath.lib  exit 1               # [win]

about:
  home: http://www.openexr.com/
  license: Modified BSD
  license_family: BSD
  license_file: LICENSE
  summary: 'IlmBase libraries required for OpenEXR.'
  doc_url: http://www.openexr.com/documentation.html

extra:
  recipe-maintainers:
    - npavlovikj
    - SylvainCorlay
    - wolfv
    - JohanMabille
